 
****************************************
Report : clock_gating
Design : ed25519
Version: S-2021.06-SP2
Date   : Thu Dec 12 19:08:03 2024
****************************************

Information: Identification of clock-gating cells has not been performed. Pre-existing clock-gating cells will not be reported. (PWR-947)


                             Clock Gating Summary
          ------------------------------------------------------------
          |    Number of Clock gating elements    |        0         |
          |                                       |                  |
          |    Number of Gated registers          |     0 (0.00%)    |
          |                                       |                  |
          |    Number of Ungated registers        |  5701 (100.00%)  |
          |                                       |                  |
          |    Total number of registers          |     5701         |
          ------------------------------------------------------------



                             Clock Gating Report by Origin
          +-------------------------------------------------+------------------+
          |                                                 |    Actual (%)    |
          |                                                 |    Count         |
          +-------------------------------------------------+------------------+
          |  Number of tool-inserted clock gating elements  |     0 (0.00%)    |
          |                                                 |                  |
          |  Number of pre-existing clock gating elements   |     0 (0.00%)    |
          |                                                 |                  |
          |  Number of gated registers                      |     0 (0.00%)    |
          |                                                 |                  |
          |  Number of tool-inserted gated registers        |     0 (0.00%)    |
          |                                                 |                  |
          |  Number of pre-existing gated registers         |     0 (0.00%)    |
          |                                                 |                  |
          |  Number of ungated registers                    |  5701 (100.00%)  |
          |                                                 |                  |
          |  Number of registers                            |     5701         |
          +-------------------------------------------------+------------------+



1
