###################################################################

# Created by write_sdc on Sun Oct 13 17:24:05 2024

###################################################################
set sdc_version 1.8

set_units -time ns -resistance kOhm -capacitance pF -power mW -voltage V       \
-current mA
set_operating_conditions slow -library slow
set_wire_load_model -name tsmc13_wl10 -library slow
set_load -pin_load 0.05 [get_ports o_out_valid]
set_load -pin_load 0.05 [get_ports {o_out_data[13]}]
set_load -pin_load 0.05 [get_ports {o_out_data[12]}]
set_load -pin_load 0.05 [get_ports {o_out_data[11]}]
set_load -pin_load 0.05 [get_ports {o_out_data[10]}]
set_load -pin_load 0.05 [get_ports {o_out_data[9]}]
set_load -pin_load 0.05 [get_ports {o_out_data[8]}]
set_load -pin_load 0.05 [get_ports {o_out_data[7]}]
set_load -pin_load 0.05 [get_ports {o_out_data[6]}]
set_load -pin_load 0.05 [get_ports {o_out_data[5]}]
set_load -pin_load 0.05 [get_ports {o_out_data[4]}]
set_load -pin_load 0.05 [get_ports {o_out_data[3]}]
set_load -pin_load 0.05 [get_ports {o_out_data[2]}]
set_load -pin_load 0.05 [get_ports {o_out_data[1]}]
set_load -pin_load 0.05 [get_ports {o_out_data[0]}]
set_max_fanout 20 [get_ports i_clk]
set_max_fanout 20 [get_ports i_rst_n]
set_max_fanout 20 [get_ports {i_data[31]}]
set_max_fanout 20 [get_ports {i_data[30]}]
set_max_fanout 20 [get_ports {i_data[29]}]
set_max_fanout 20 [get_ports {i_data[28]}]
set_max_fanout 20 [get_ports {i_data[27]}]
set_max_fanout 20 [get_ports {i_data[26]}]
set_max_fanout 20 [get_ports {i_data[25]}]
set_max_fanout 20 [get_ports {i_data[24]}]
set_max_fanout 20 [get_ports {i_data[23]}]
set_max_fanout 20 [get_ports {i_data[22]}]
set_max_fanout 20 [get_ports {i_data[21]}]
set_max_fanout 20 [get_ports {i_data[20]}]
set_max_fanout 20 [get_ports {i_data[19]}]
set_max_fanout 20 [get_ports {i_data[18]}]
set_max_fanout 20 [get_ports {i_data[17]}]
set_max_fanout 20 [get_ports {i_data[16]}]
set_max_fanout 20 [get_ports {i_data[15]}]
set_max_fanout 20 [get_ports {i_data[14]}]
set_max_fanout 20 [get_ports {i_data[13]}]
set_max_fanout 20 [get_ports {i_data[12]}]
set_max_fanout 20 [get_ports {i_data[11]}]
set_max_fanout 20 [get_ports {i_data[10]}]
set_max_fanout 20 [get_ports {i_data[9]}]
set_max_fanout 20 [get_ports {i_data[8]}]
set_max_fanout 20 [get_ports {i_data[7]}]
set_max_fanout 20 [get_ports {i_data[6]}]
set_max_fanout 20 [get_ports {i_data[5]}]
set_max_fanout 20 [get_ports {i_data[4]}]
set_max_fanout 20 [get_ports {i_data[3]}]
set_max_fanout 20 [get_ports {i_data[2]}]
set_max_fanout 20 [get_ports {i_data[1]}]
set_max_fanout 20 [get_ports {i_data[0]}]
set_max_fanout 20 [get_ports i_isFirst]
set_max_fanout 20 [get_ports i_input_done]
set_ideal_network [get_ports i_clk]
create_clock [get_ports i_clk]  -period 2.58  -waveform {0 1.29}
set_clock_latency 0.5  [get_clocks i_clk]
set_clock_uncertainty 0.1  [get_clocks i_clk]
set_input_delay -clock i_clk  1.29  [get_ports i_clk]
set_input_delay -clock i_clk  1.29  [get_ports i_rst_n]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[31]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[30]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[29]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[28]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[27]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[26]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[25]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[24]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[23]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[22]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[21]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[20]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[19]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[18]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[17]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[16]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[15]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[14]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[13]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[12]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[11]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[10]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[9]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[8]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[7]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[6]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[5]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[4]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[3]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[2]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[1]}]
set_input_delay -clock i_clk  1.29  [get_ports {i_data[0]}]
set_input_delay -clock i_clk  1.29  [get_ports i_isFirst]
set_input_delay -clock i_clk  1.29  [get_ports i_input_done]
set_output_delay -clock i_clk  1.29  [get_ports o_out_valid]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[13]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[12]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[11]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[10]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[9]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[8]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[7]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[6]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[5]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[4]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[3]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[2]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[1]}]
set_output_delay -clock i_clk  1.29  [get_ports {o_out_data[0]}]
